services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - smartbin-net

  producer:
    build: .
    command: python producer.py --verbose --host mosquitto
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
    volumes:
      - ./data:/app/data
    networks:
      - smartbin-net
    depends_on:
      - mosquitto

  consumer:
    build: .
    command: >
      python consumer.py
      --verbose
      --host mosquitto
      --topic smartbin/bin-01/pir-01/events
      --out /app/data/motion_events.jsonl
    volumes:
      - ./data:/app/data
    networks:
      - smartbin-net
    depends_on:
      - mosquitto

  api:
    build: .
    command: python api.py
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - MQTT_BROKER=mosquitto
    networks:
      - smartbin-net
    depends_on:
      - mosquitto

  virtual_sensor_rules:
    build: .
    command: python virtual_sensor_rules.py --broker mosquitto
    networks:
      - smartbin-net
    depends_on:
      - mosquitto
      - producer

  virtual_sensor_ml:
    build: .
    command: python virtual_sensor_ml.py --broker mosquitto
    volumes:
      - ./models_v_s:/app/models_v_s
    networks:
      - smartbin-net
    depends_on:
      - mosquitto
      - producer
  upload:
    build: .
    command: python upload.py
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
    depends_on:
      - mosquitto

  asyncapi-docs:
    image: python:3.11-slim
    working_dir: /app
    command: python serve_yaml.py
    ports:
      - "5002:5002"
    volumes:
      - ./asyncapi.yml:/app/asyncapi.yml:ro
      - ./serve_yaml.py:/app/serve_yaml.py:ro

networks:
  smartbin-net:
    driver: bridge
